# Generated by Django 5.0.3 on 2024-03-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='seller/banner'),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
