# Generated by Django 5.0.3 on 2024-03-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_seller_email_remove_seller_name_seller_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
    ]
